/* RTC<component>
 *
 * Copyright (C) 2011
 *     Geoffrey Biggs
 *     RT-Synthesis Research Group
 *     Intelligent Systems Research Institute,
 *     National Institute of Advanced Industrial Science and Technology (AIST),
 *     Japan
 *     All rights reserved.
 * Licensed under the Eclipse Public License -v 1.0 (EPL)
 * http://www.opensource.org/licenses/eclipse-1.0.txt
 *
 * The ??? interface.
 */


#ifndef <interface>_IDL_
#define <interface>_IDL_

module <module>
{
    interface <interface>
    {
    };
}; // module <module>

#endif // <interface>_IDL_

